FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends curl && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

COPY parser_service/requirements.txt .

RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir --upgrade -r requirements.txt

COPY parser_service/ .
COPY app/models/ ./app/models/
COPY app/__init__.py ./app/__init__.py

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001"]
